### PR TITLE
background to v6 and readability improvements

### PR DESCRIPTION
**Pull request by simi**
Hello. Thanks for great page!

I just noticed there's missing background color for v6. Here's my idea how to solve that. I had to change font color also since it was really hard for me to read gray text on palegreen background and I wasn't able to find another green to fit current color scheme.
# preview

screenshot-localhost 8080 2016-04-27 22-37-05

### CODE REVIEW

**Comment by williamkapke** [comment]
Ah- good catch. When v6 went out, it automatically started picking up v7 for the nightlies... but as you found in the css- I didn't define color for it :(

The `index.html` is generated from the `index.jade` file by running `node build.js`. Can you update the jade file, run `node build.js` and then commit the 2 files `index.html` and `index.jade`?

**Comment by simi** [comment]
done

**Comment by williamkapke** [comment]
Looks great- Thank YOU!

**Comment by simi** [comment]
:confetti_ball:

**Pull request merged**
