### PR TITLE
run tests with callbacks and add node.js 0.10

### PR DESCRIPTION
**Pull request by dougwilson**
This is a fairly basic pass at simply converting the Promise-based tests to callbacks and add Node.js 0.10 for #12. I wasn't sure of the environment the `test.js` file run it, and it seemed pretty vanilla, so went with callbacks. Another possible solution would be to simply add Bluebird or another promise implementation (trusting that it does not alter any global state) and use that and keep the test runner the same.

🚆 

I tried to keep the same code style, but I'm not sure how well I did that, because I wasn't quite sure on the style in various places :)

I don't personally need this, but saw #12 and was bored 👽

### CODE REVIEW

**Comment by williamkapke** [comment]
This seems to work great in my testing so far.

> I tried to keep the same code style, but I'm not sure how well I did that, because I wasn't quite sure on the style in various places :)

...heh- yeah. I switch through so many projects, I mix them up often if there isn't a linter to remind me. I guess I try to lean toward using [standard](https://www.npmjs.com/package/standard) now.

**Comment by williamkapke** [comment]
Hm. You might want to look at the diff on 8f4f8e32668524ea8f5b5e142bb4ca8e79cd07f5. It is saying `Promise.all` and `Promise.race` are not there.. on 0.12? I'm pretty sure they are.

Also, something I didn't think of at first... v0.10 does not support the `--es_staging` flag so it gives a warning when it runs... the output is the same as without a flag. The `--es_staging` files are not used on the website (they are just there to track the data for possible future use) so it's not really a big deal.

**Comment by dougwilson** [comment]
Yea, i was looking at that commit and scratching my head about the diffs for 0.12. I'll be taking a look when i get home in a bit 😊

**Comment by williamkapke** [comment]
Awesome work for a "basic pass" though!

**Comment by dougwilson** [comment]
I found that the changes in 0.12 is because I forgot that back then, `process.nextTick` only took a single argument. #14 fixes this :)

**Pull request merged**
